[main]
font=JetBrainsMono Nerd Font:size=10,JetBrainsMono NF:size=10,monospace:size=10
prompt=""
width=18
lines=4
inner-pad=8

anchor=top-right
x-margin=20
y-margin=45

[colors]
# e6 в конце — это прозрачность. Можно менять: 
# ff - глухой цвет, 00 - полностью прозрачный, 80 - половина.
background=1e1e2ee6
text=cdd6f4ff
selection=313244ff
selection-text=f38ba8ff
border=f38ba8ff


[border]
width=2
radius=10
